export const MOCK_STUDENTS = [
  {
    id: 'STU001',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '+1 234 567 8901',
    guardian: 'Jane Doe',
    guardianContact: '+1 234 567 8902',
    skills: ['React', 'Tailwind', 'Node.js'],
    hobbies: ['Photography', 'Hiking'],
    achievements: [],
    medicalInfo: 'No known allergies.',
    assignedEvents: ['EVT001'],
  },
  {
    id: 'STU002',
    name: 'Alice Smith',
    email: 'alice.smith@example.com',
    phone: '+1 234 567 8903',
    guardian: 'Bob Smith',
    guardianContact: '+1 234 567 8904',
    skills: ['UI/UX Design', 'Figma', 'Adobe XD'],
    hobbies: ['Painting', 'Reading'],
    achievements: [],
    medicalInfo: 'Peanut allergy.',
    assignedEvents: ['EVT002'],
  },
  {
    id: 'STU003',
    name: 'Michael Brown',
    email: 'michael.brown@example.com',
    phone: '+1 234 567 8905',
    guardian: 'Sarah Brown',
    guardianContact: '+1 234 567 8906',
    skills: ['Python', 'Data Science'],
    hobbies: ['Chess', 'Gaming'],
    achievements: [],
    medicalInfo: 'None.',
    assignedEvents: [],
  },
  {
    id: 'STU004',
    name: 'Emily Davis',
    email: 'emily.davis@example.com',
    phone: '+1 234 567 8907',
    guardian: 'Robert Davis',
    guardianContact: '+1 234 567 8908',
    skills: ['Public Speaking', 'Leadership'],
    hobbies: ['Debating', 'Traveling'],
    achievements: [],
    medicalInfo: 'Asthma.',
    assignedEvents: ['EVT001', 'EVT003'],
  },
  {
    id: 'STU005',
    name: 'Chris Wilson',
    email: 'chris.wilson@example.com',
    phone: '+1 234 567 8909',
    guardian: 'Mary Wilson',
    guardianContact: '+1 234 567 8910',
    skills: ['Java', 'SQL'],
    hobbies: ['Guitar', 'Singing'],
    achievements: [],
    medicalInfo: 'None.',
    assignedEvents: ['EVT003'],
  },
];

export const MOCK_EVENTS = [
  {
    id: 'EVT001',
    name: 'Annual Tech Symposium',
    category: 'Academic',
    date: '2026-04-15',
    time: '09:00 AM',
    venue: 'Main Auditorium',
    maxParticipants: 50,
    status: 'Active',
    description: 'A gathering of technology enthusiasts to share knowledge and innovations.',
    participants: ['STU001', 'STU004'],
  },
  {
    id: 'EVT002',
    name: 'Inter-College Sports Fest',
    category: 'Sports',
    date: '2026-05-10',
    time: '08:00 AM',
    venue: 'Sports Complex',
    maxParticipants: 100,
    status: 'Active',
    description: 'Compete in various sports activities and showcase your athletic skills.',
    participants: ['STU002'],
  },
  {
    id: 'EVT003',
    name: 'Cultural Night 2026',
    category: 'Cultural',
    date: '2026-06-20',
    time: '06:00 PM',
    venue: 'Open Grounds',
    maxParticipants: 200,
    status: 'Active',
    description: 'Celebrate diversity through music, dance, and art performances.',
    participants: ['STU004', 'STU005'],
  },
];

export const MOCK_ANNOUNCEMENTS = [
  {
    id: 'ANN001',
    title: 'Registration Open for Tech Symposium',
    category: 'Event Update',
    date: '2026-03-20',
    content: 'Students can now register for the upcoming Tech Symposium. Visit the events page for more details.',
    targetAudience: 'All Students',
    status: 'Published',
  },
  {
    id: 'ANN002',
    title: 'Urgent: Room Change for Sports Fest Meeting',
    category: 'Urgent',
    date: '2026-03-22',
    content: 'The meeting for Sports Fest participants has been moved to Room 302.',
    targetAudience: 'Specific Event',
    status: 'Published',
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: 'NOT001',
    type: 'UserPlus',
    message: 'New student John Doe has been registered',
    timestamp: '2 hours ago',
    isRead: false,
  },
  {
    id: 'NOT002',
    type: 'CalendarPlus',
    message: 'Student Alice Smith assigned to Inter-College Sports Fest',
    timestamp: '5 hours ago',
    isRead: true,
  },
];
